trigger:
  paths:
    include:
      - windows\windows_security_baselines\generate_microsoft_edge_baseline.yml

extends:
  template: ../../.azure-pipelines/templates/generate_dsc_from_baseline.yml
  parameters:
    baselineZipUrl: "https://download.microsoft.com/download/8/5/C/85C25433-A1B0-4FFA-9429-7E023E7DA8D8/Microsoft%20Edge%20v80.zip"