name: Create Windows client baseline DSC

on:
  push:
    branches: 
      - master
    paths:
      - 'windows/desired_state_configuration/**'

jobs:
  create_mof:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate MOF
      run: ./windowsh/desired_state_configuration/scripts/generate_mofs.ps1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload Release Asset (Required Modules)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./windows/desired_state_configuration/scripts/install_required_modules.ps1
        asset_name: install_required_modules.ps1
        asset_content_type: text/plain

    - name: Upload Release Asset (MOF)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./mof/localhost.mof
        asset_name: client_baseline.mof
        asset_content_type: text/plain
