name: Create client baseline MOF

on:
  push:
    branches: 
      - master

jobs:
  create_mof:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate MOF
      run: |
        Set-Location .\windows\desired_state_configuration

        #Load all policies
        $localGroupPolicies = Get-ChildItem .\data\policies\ | ForEach-Object{
            (Import-PowerShellDataFile -Path $_.FullName).Policies
        }

        #Setup configuration data
        $ConfigurationData =
        @{
            AllNodes =
            @(
                @{
                    NodeName           = "localhost"
                    LocalGroupPolicies = $localGroupPolicies
                }
            )
        }

        # Dot source the client configuration
        . ./configurations/ClientBaseline.ps1

        # Generate MOFs
        ClientBaseline -ConfigurationData $ConfigurationData -OutputPath ./mof/

    - uses: actions/upload-artifact@v2
      with:
        name: client_baseline_mof
        path: ./desired_state_configuration/mof/localhost.mof
